### ISSUE TITLE
java 与业务对接，是不是使用server 的10002端口啊

### ISSUE THREAD

**Issue by huazaihuola** [openim-sigs/openim-java-sdk#1]
java 与业务对接，是不是使用server 的10002端口啊

**Comment by asgardjh** [comment]
配置格式如下：
openim:
  api: http://openim-web.host.fit
  #  下面可以不配置，默认按以下规则生成
  #  apiApi: http://openim-web.host.fit/api
  #  apiChat: http://openim-web.host.fit/chat
  #  apiAdmin: http://openim-web.host.fit/complete_admin
  apiApi: http://192.168.0.101:10002
  apiChat: http://192.168.0.101:10008
  apiAdmin: http://192.168.0.101:10009
