### ISSUE TITLE
account register API has exception

### ISSUE THREAD

**Issue by OL1V1A** [openim-sigs/openim-java-sdk#3]
![image](https://github.com/openim-sigs/openim-java-sdk/assets/26080323/dccdf771-27a9-47b8-8675-7367f84ecfdb)
invoking this method reported an error.
{
    "errCode": 1001,
    "errMsg": "ArgsError",
    "errDlt": "header must have operationID: 1001 ArgsError"
}

**Comment by asgardjh** [comment]
Thank you, the issue has been resolved,Add support for operationId.
